services:
  yk-yt:
    image: yk:latest
    container_name: yk-yt
    restart: unless-stopped
    network_mode: host
    tty: true
    stdin_open: true

    environment:
      # YK_PROXIES: socks5://127.0.0.1:1080
      YK_LOG_PATH: /tmp/log
      YK_DELAY: 300 # big delay for yt
      # YK_NTFY: test_channel
      YK_SRC_LISTS: /tmp/list-yt.txt
    build:
      # context: https://github.com/ntrrpt/yakayaka.git
      context: .
      args:
        # update yt-dlp/deps on every container start
        # (because google likes to break things)
        FORCE_UV_SYNC_ON_START: YES
    volumes:
      - ./:/out
      - ./list-yt.txt:/tmp/list-yt.txt
      - ./:/tmp/log

    command: ['--yta']

  yk-tw:
    image: yk:latest
    container_name: yk-tw
    restart: unless-stopped
    network_mode: host
    tty: true
    stdin_open: true
    
    environment:
      # YK_PROXIES: socks5://127.0.0.1:1080
      YK_LOG_PATH: /tmp/log
      YK_DELAY: 15
      YK_SRC_LISTS: /tmp/list-tw.txt
    build:
      # context: https://github.com/ntrrpt/yakayaka.git
      context: .
      args:
        # (and twitch sometimes too)
        FORCE_UV_SYNC_ON_START: YES
    volumes:
      - ./:/out
      - ./list-tw.txt:/tmp/list-tw.txt
      - ./:/tmp/log

    command: []
